export const Students = [
    {
        stuID: 1,
        StudentName: 'Ursula Owens',
        address: 'Watson Lake',
        phone: '0478386175',
        dob: new Date(2000, 9, 23),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 2,
        StudentName: 'Plato Massey',
        address: 'Lelystad',
        phone: '0546956463',
        dob: new Date(2000, 8, 15),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 3,
        StudentName: 'Pamela Long',
        address: 'Reinbek',
        phone: '0326242264',
        dob: new Date(1998, 11, 11),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 4,
        StudentName: 'Prescott Richmond',
        address: 'Goiânia',
        phone: '0973760989',
        dob: new Date(1997, 7, 3),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 5,
        StudentName: 'Warren Massey',
        address: 'Cajazeiras',
        phone: '0452377030',
        dob: new Date(1997, 7, 12),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 6,
        StudentName: 'Calvin Rivas',
        address: 'Darwin',
        phone: '0662648594',
        dob: new Date(1997, 1, 3),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 7,
        StudentName: 'Calista May',
        address: 'Cañas',
        phone: '0653874683',
        dob: new Date(1997, 4, 3),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 8,
        StudentName: 'Kamal Beck',
        address: 'Shaanxi',
        phone: '0332128381',
        dob: new Date(2001, 5, 12),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 9,
        StudentName: 'Rigel Watkins',
        address: 'Pontianak',
        phone: '0339832770',
        dob: new Date(1995, 8, 15),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 10,
        StudentName: 'Abra Knapp',
        address: 'Tauranga',
        phone: '0223063341',
        dob: new Date(2000, 3, 12),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 11,
        StudentName: 'Jolie Hammond',
        address: 'Tual',
        phone: '0550495516',
        dob: new Date(1997, 4, 22),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 12,
        StudentName: 'Karyn Page',
        address: 'Okigwe',
        phone: '0877854525',
        dob: new Date(2000, 2, 28),
        age: '',
        gender: 'Male',
    },
    {
        stuID: 13,
        StudentName: 'Penelope Bartlett',
        address: 'Meycauayan',
        phone: '0339352156',
        dob: new Date(1996, 12, 12),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 14,
        StudentName: 'Melvin Hamilton',
        address: 'Dublin',
        phone: '0777893101',
        dob: new Date(1996, 6, 5),
        age: '',
        gender: 'Female',
    },
    {
        stuID: 15,
        StudentName: 'Chandler Kidd',
        address: 'Pinetown',
        phone: '0466877475',
        dob: new Date(1995, 11, 8),
        age: '',
        gender: 'Male',
    },
];
